# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Build Tokens

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Build
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: commit built token files
        file_pattern: build/
